name: project1 action

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout the code
      uses: actions/checkout@v2
      
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '21' 
        distribution: 'temurin'

    - name: Cache Maven dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
          
    - name: build the project with mvn
      run: cd java-maven-sonar-argocd-helm-k8s/spring-boot-app && mvn clean package -DskipTests
      
    - name: SonarQube Scan
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # Token should be saved as a secret in your repo's settings
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL}}
      run: mvn sonar:sonar \
        -Dsonar.projectKey=Project1 \
        -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
        -Dsonar.login=${{ secrets.SONAR_TOKEN }}















        
     
