name: project1 action

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: checkout the code
      uses: actions/checkout@v2
      
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '21' 
        distribution: 'temurin'

    - name: Cache Maven dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
          
    - name: build the project with mvn
      run: cd java-maven-sonar-argocd-helm-k8s/spring-boot-app && mvn clean package -DskipTests
      
    # - name: SonarQube Scan
    #   env:
    #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
    #       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    #       SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
    #   run: cd java-maven-sonar-argocd-helm-k8s/spring-boot-app && mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Project1
        

    # - name: Setup docker buildx
    #   uses:  docker/setup-buildx-action@v2
      
    # - name: Login to DockrHub
    #   uses: docker/login-action@v2
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}

    # - name: Build and push docker image
    #   run: |
    #     BUILD_TAG=${{ github.run_number }}
    #     docker build -t ${{ secrets.DOCKER_USERNAME }}/my-app:${BUILD_TAG} ./java-maven-sonar-argocd-helm-k8s/spring-boot-app
    #     docker push ${{ secrets.DOCKER_USERNAME }}/my-app:${{BUILD_TAG}}

    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: manojtiwari000/my-app
      
    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
     
   
   
       













        
     
